apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-mgmt-app-deploy
  labels:
    name: book-mgmt-app-deploy
    app: book-management
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      name: book-mgmt-app-pod
      app: book-management
  template:
    metadata:
      name: book-mgmt-app-pod
      labels:
        name: book-mgmt-app-pod
        app: book-management
    spec:
      containers:
        - name: book-management-app-image
          image: APP_DOCKER_IMG_TAG
          ports:
            - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: book-management
                name: book-mgmt-api-pod
            topologyKey: "kubernetes.io/hostname"